
trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

variables:
  pythonVersion: "3.11"
  # Set these in the pipeline or a variable group:
  # AZURE_SUBSCRIPTION: <service-connection-name>
  # WEBAPP_NAME: <your-web-app-name>
  # AZURE_RESOURCE_GROUP: <rg>

stages:
- stage: BuildTest
  jobs:
  - job: build_and_test
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'

    - script: pip install -r requirements.txt
      displayName: Install dependencies

    - script: pytest --maxfail=1 --disable-warnings --cov=src --cov-report=xml --cov-report=html --cov-fail-under=80
      displayName: Run tests with coverage

    - task: PublishCodeCoverageResults@2
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage.xml'
        reportDirectory: '$(System.DefaultWorkingDirectory)/htmlcov'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/site.zip'
        replaceExistingArchive: true

    - publish: '$(Build.ArtifactStagingDirectory)/site.zip'
      artifact: drop

- stage: Deploy
  dependsOn: BuildTest
  condition: and(succeeded(), ne(variables['WEBAPP_NAME'], ''))
  jobs:
  - deployment: webapp
    environment: 'prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: Deploy to Azure Web App
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              appName: '$(WEBAPP_NAME)'
              package: '$(Pipeline.Workspace)/drop/site.zip'
              startupCommand: 'python -m uvicorn src.api.main:app --host 0.0.0.0 --port 8000'
